/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/eJSEuW3mgR1
 */

const info = [
  {
    name: 'Абажур',
    type: 'Искаженный жест',
    actuality: 'Современный',
    dialect: 'Международный'
  }
];

export function Details() {
  return (
    <div className="flex justify-between bg-black">
      {info.map((jest) => (<h1 key={jest.name} className="w-1/5 text-[#3EA2FF] pl-4 text-4xl">{jest.name}</h1>))}
      <div className="flex justify-end items-start pt-1 gap-4">
        <div className="flex justify-start h-auto items-start gap-4">
          {info.map((jest) => (
            <div key={jest.name} className="flex flex-col justify-center items-start px-4 border border-[#58a6ff] rounded-lg dark:border-neutral-800 w-[160px] h-[50px]">
              <span className="text-[#c9d1d9] text-[10px]">Вид речи:</span>
              <span className="text-[#58a6ff] text-[13.33px] font-semibold">{jest.type}</span>
            </div>
          ))}
        </div>
        <div className="bg-black flex justify-start items-start gap-4">
          {info.map((jest) => (
            <div key={jest.name} className="flex flex-col justify-center items-start px-4 border border-[#58a6ff] rounded-lg dark:border-neutral-800 w-[160px] h-[50px]">
              <span className="text-[#c9d1d9] text-[10px]">Актуальность:</span>
              <span className="text-[#58a6ff] text-[13.33px] font-semibold">{jest.actuality}</span>
            </div>
          ))}
        </div>
        <div className="bg-black flex justify-start items-start gap-4">
          {info.map((jest) => (
            <div key={jest.name} className="flex flex-col justify-center items-start px-4 border border-[#58a6ff] rounded-lg dark:border-neutral-800 w-[160px] h-[50px]">
              <span className="text-[#c9d1d9] text-[10px]">Диалект:</span>
              <span className="text-[#58a6ff] text-[13.33px] font-semibold">{jest.dialect}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
