/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QkOy2CWBbgQ
 */
import { useRouteError } from "react-router-dom";

export function Error() {
  const error = useRouteError();
  console.error(error);

  return (
    (<div
      className="flex flex-col items-center justify-center w-full min-h-screen py-12 space-y-4 text-center">
      <div className="space-y-2">
        <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl">{error.message}</h1>
        <p
          className="max-w-[600px] text-gray-500 md:text-xl/relaxed dark:text-gray-400">
          {error.statusText}
        </p>
      </div>
      <a
        className="inline-flex h-10 items-center rounded-md border border-neutral-200 border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-neutral-800"
        href="">
        Return to website
      </a>
    </div>)
  );
}
