/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gvQbaHqgfXC
 */
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";

export function Filters() {
  return (
    <div className="flex items-center justify-between gap-4 bg-black px-4 pb-2">
      <Select>
        <SelectTrigger
          className="border-none bg-[#333] text-white"
          id="dialect"
        >
          <SelectValue placeholder="Диалект" />
        </SelectTrigger>
        <SelectContent className="bg-[#333]" position="popper">
          <SelectItem value="moscow">Московский</SelectItem>
          <SelectItem value="petersburg">Петербургский</SelectItem>
        </SelectContent>
      </Select>
      <Select>
        <SelectTrigger className="border-none bg-[#333] text-white" id="speech">
          <SelectValue placeholder="Вид Речи" />
        </SelectTrigger>
        <SelectContent className="bg-[#333]" position="popper">
          <SelectItem value="formal">Формальный</SelectItem>
          <SelectItem value="informal">Неформальный</SelectItem>
        </SelectContent>
      </Select>
      <Select>
        <SelectTrigger className="border-none bg-[#333] text-white" id="type">
          <SelectValue placeholder="Вид" />
        </SelectTrigger>
        <SelectContent className="bg-[#333]" position="popper">
          <SelectItem value="type1">Тип 1</SelectItem>
          <SelectItem value="type2">Тип 2</SelectItem>
        </SelectContent>
      </Select>
      <Select>
        <SelectTrigger
          className="border-none bg-[#333] text-white"
          id="relevance"
        >
          <SelectValue placeholder="Актуальность" />
        </SelectTrigger>
        <SelectContent className="bg-[#333]" position="popper">
          <SelectItem value="relevant">Актуально</SelectItem>
          <SelectItem value="irrelevant">Неактуально</SelectItem>
        </SelectContent>
      </Select>
      <Select>
        <SelectTrigger
          className="border-none bg-[#333] text-white"
          id="gesture-dictionaries"
        >
          <SelectValue placeholder="Жестовые словари" />
        </SelectTrigger>
        <SelectContent className="bg-[#333]" position="popper">
          <SelectItem value="dictionary1">Словарь 1</SelectItem>
          <SelectItem value="dictionary2">Словарь 2</SelectItem>
        </SelectContent>
      </Select>
    </div>
  );
}
