/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gvQbaHqgfXC
 */
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"

export function Filters() {
  return (
    (<div className="bg-black px-4 py-2 flex justify-between items-center gap-4">
      <Select>
        <SelectTrigger className="text-white bg-[#333] border-none" id="dialect">
          <SelectValue placeholder="Диалект" />
        </SelectTrigger>
        <SelectContent className="bg-[#333]" position="popper">
          <SelectItem value="moscow">Московский</SelectItem>
          <SelectItem value="petersburg">Петербургский</SelectItem>
        </SelectContent>
      </Select>
      <Select>
        <SelectTrigger className="text-white bg-[#333] border-none" id="speech">
          <SelectValue placeholder="Вид Речи" />
        </SelectTrigger>
        <SelectContent className="bg-[#333]" position="popper">
          <SelectItem value="formal">Формальный</SelectItem>
          <SelectItem value="informal">Неформальный</SelectItem>
        </SelectContent>
      </Select>
      <Select>
        <SelectTrigger className="text-white bg-[#333] border-none" id="type">
          <SelectValue placeholder="Вид" />
        </SelectTrigger>
        <SelectContent className="bg-[#333]" position="popper">
          <SelectItem value="type1">Тип 1</SelectItem>
          <SelectItem value="type2">Тип 2</SelectItem>
        </SelectContent>
      </Select>
      <Select>
        <SelectTrigger className="text-white bg-[#333] border-none" id="relevance">
          <SelectValue placeholder="Актуальность" />
        </SelectTrigger>
        <SelectContent className="bg-[#333]" position="popper">
          <SelectItem value="relevant">Актуально</SelectItem>
          <SelectItem value="irrelevant">Неактуально</SelectItem>
        </SelectContent>
      </Select>
      <Select>
        <SelectTrigger className="text-white bg-[#333] border-none" id="gesture-dictionaries">
          <SelectValue placeholder="Жестовые словари" />
        </SelectTrigger>
        <SelectContent className="bg-[#333]" position="popper">
          <SelectItem value="dictionary1">Словарь 1</SelectItem>
          <SelectItem value="dictionary2">Словарь 2</SelectItem>
        </SelectContent>
      </Select>
    </div>)
  );
}
